spp_vf: change inline func calls static inside
Change `extern inline` funcitons to static to avoid compile error like
as following in some environments.

    error: ‘rte_eth_tx_burst’ is static but used in inline function
    ‘spp_eth_tx_burst’ which is not static

In this case, static rte_eth_tx_burst() should not be called from inline
function.

Signed-off-by: Yasufumi Ogawa <ogawa.yasufumi@lab.ntt.co.jp>