spp_nfv: remove declaration in for loop
For some environment, declaration in for loop cause an error.

  error: ‘for’ loop initial declarations are only allowed in C99 mode

This update is move this declaration from.

Signed-off-by: Yasufumi Ogawa <ogawa.yasufumi@lab.ntt.co.jp>