vf: change char length to avoid compile error
Change character length of SPP_CMD_VALUE_BUFSZ to avoid compile error
on gcc-7.

build error:
spp/src/vf/command_proc.c:231:37:
  error: ‘%s’ directive writing up to 127 bytes into a region of
         size 112 [-Werror=format-overflow=]
    sprintf(message, "unknown command(%s)", decode_error->value);
                                      ^~    ~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10:
  note: ‘__builtin___sprintf_chk’ output between 18 and 145 bytes into a
        destination of size 128
    return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It is acceptable to change buf size from 128 to 111 because command
is not so long to exceed over 100 chars in spp_vf.

Signed-off-by: Kenta Shinohara <shinohara.kenta@lab.ntt.co.jp>
Acked-by: Yasufumi Ogawa <ogawa.yasufumi@lab.ntt.co.jp>